#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server.
# Configure HAproxy so that it send traffic to web-01 and web-02

sudo apt-get -y update
apt-get -y install haproxy

server_config=\
"
frontend  sobil-frontend
        bind *:80
        mode http
        default_backend sobil-backend

backend sobil-backend
        balance roundrobin
        server 428425-web-01 3.90.84.253 check
        server 428425-web-02 3.83.227.85 check
"
echo "$server_config" | sudo tee -a /etc/haproxy/haproxy.cfg

echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

sudo service haproxy restart
